import { useEffect, useRef, useState } from "react";
import { Link, navigate } from "../router";
import { ConnectShopify } from "../components/ConnectShopify";
import { COFFEE_STANDARD_URL, COFFEE_STANDARD_VERSION } from "../copy";

// ---------------------------------------------------------------------------
// THE TWO LAYERS, MADE VISIBLE (v4.1).
//
// This page has always run the GENERAL engine — a per-product buyer task generated by
// `buildBuyerTask` — and has never said so. A coffee merchant and a bath-mat merchant got
// the same unlabelled table, while the landing page told both of them that AisleLens
// "executes a published buying standard against the page". The builder of this product
// could not answer which layer ran on a non-coffee store; no visitor could either.
//
// Now the result says which layer it is, and a published standard is one click away when
// one might cover the product.
// ---------------------------------------------------------------------------

interface PeerRate {
  entryId: string; label: string;
  adjudicated: number; failed: number; passed: number;
  failPct: number; undecided: number; asked: number;
}
interface StandardRun {
  ok: boolean;
  productUrl: string;
  notApplicable?: { verdict: string; signal: string; text: string | null; detail: string; skipped: Array<{ entry: string; reason: string; detail: string }> };
  error?: string; errorKind?: string; retryable?: boolean;
  standard?: { id: string; version: string; hash: string; slug: string; url: string; title: string };
  entryUrls?: Record<string, string>;
  peers?: PeerRate[];
  result?: TestResult;
  ranAt?: string;
}

/**
 * The peer sentence, and the denominator trap it exists to avoid.
 *
 * ⚠️ NEVER "of 100". Five of the ten measured coffee entries were asked of fewer than 100
 * products, each for a recorded reason, and one — the delivery entry — could only be
 * DECIDED on 74 of the 100 it was asked, because 26 returned "requires store access".
 * Counting an undecided row as a pass is a different measurement, and this repo has
 * published both by accident before (v1.1 stated 45%, the adjudicated reading is 60.8%).
 * So the sentence names the denominator it actually used, every time.
 */
function peerSentence(p: PeerRate, storePassed: boolean): string {
  const base = p.undecided > 0
    ? `${p.failed} of the ${p.adjudicated} coffee stores we could decide (of ${p.asked} asked)`
    : `${p.failed} of ${p.adjudicated} coffee stores`;
  return storePassed
    ? `${base} don't state this. This one does.`
    : `${base} don't state this either.`;
}

/** Which CATEGORY_CLAIMS branch the general engine matched, inferred from the row labels
 *  it produced — zero extra cost, because the response already carries them. `Single-origin`
 *  is asked ONLY by the coffee branch, so its presence means the engine read this page's
 *  product_type or title as coffee. It decides the button's FRAMING, never the outcome:
 *  the standard's own applicability gate is the authority and refuses honestly. */
function looksLikeCoffee(r: TestResult): boolean {
  return r.assertions.some((a) => /^single-origin$/i.test(a.label.trim()));
}

// PHASE B — the AI-buyer PRODUCT TEST result page. Paste a Shopify product URL →
// a buyer task of 4–6 requirements run as honest, evidence-availability assertions
// against public data → an assertion-table result. This is the funnel mechanic the
// repositioned hero promises: the interface IS the test runner.

// The four honest result states. `pass_no_blocking` renders deliberately WEAKER
// than `pass_evidenced` (neutral glyph + muted label): an inference from absence
// is never presented as proof.
type AssertionStatus = "pass_evidenced" | "pass_no_blocking" | "not_proven" | "requires_store_access";
interface Assertion {
  label: string; status: AssertionStatus; detail: string;
  evidenceQuote?: string; evidenceSurface?: string; surfacesChecked: string[];
}
interface TestResult {
  ok: boolean; error?: string; errorKind?: string; productUrl: string;
  storeName: string | null; productName: string | null; task: string;
  assertions: Assertion[];
  evidencedCount: number; noBlockingCount: number; notProvenCount: number; requiresAccessCount: number;
  total: number; surfacesChecked: string[]; notInspectable: string[];
  suggestedCorrections: string[]; suggestedCorrection: string | null;
  deferred: Assertion[];
  testedAt?: string; cached?: boolean;
  /** V2 §2.3 — a fetch tier was refused upstream and the test ran on partial data.
   *  The affected rows carry their own accurate reason; this drives the banner. */
  degraded?: boolean;
  /** The failure is an upstream limit, not a verdict — offer a retry, not a shrug. */
  retryable?: boolean;
  /** Carries THIS result through install so the first authenticated screen is the
   *  merchant's own test, continued. Also ties a later install click back to it. */
  testToken?: string;
}

const RESULT_LABEL: Record<AssertionStatus, string> = {
  pass_evidenced: "Proven",
  pass_no_blocking: "No blocking evidence",
  not_proven: "Not proven",
  requires_store_access: "Requires store access",
};
const RESULT_MARK: Record<AssertionStatus, string> = {
  pass_evidenced: "✓", pass_no_blocking: "–", not_proven: "✕", requires_store_access: "○",
};

function Row({ a }: { a: Assertion }) {
  return (
    <tr className={`pt-row pt-${a.status}`}>
      <td className="pt-req">{a.label}</td>
      <td className="pt-res">
        <span className="pt-mark" aria-hidden>{RESULT_MARK[a.status]}</span>
        <span>
          <b>{RESULT_LABEL[a.status]}</b>
          <div className="pt-detail">{a.detail}</div>
          {a.evidenceQuote && (
            <div className="pt-quote">
              “{a.evidenceQuote}”{a.evidenceSurface ? <span className="pt-src"> — {a.evidenceSurface}</span> : null}
            </div>
          )}
        </span>
      </td>
    </tr>
  );
}

/** Coarse relative time for the cache label. Results now live 7 days (V2 §2.4), so
 *  this has to read naturally all the way out to "6 days ago". */
function timeAgo(iso: string): string {
  const mins = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 60000));
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins} minute${mins === 1 ? "" : "s"} ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs} hour${hrs === 1 ? "" : "s"} ago`;
  const days = Math.round(hrs / 24);
  return `${days} day${days === 1 ? "" : "s"} ago`;
}

/** "3 proven · 1 no blocking evidence · 1 unproven · 1 needs store access (not counted against you)" */
function breakdown(r: TestResult): string {
  const parts = [`${r.evidencedCount} proven`];
  if (r.noBlockingCount) parts.push(`${r.noBlockingCount} no blocking evidence`);
  if (r.notProvenCount) parts.push(`${r.notProvenCount} unproven`);
  if (r.requiresAccessCount) parts.push(`${r.requiresAccessCount} need store access (not counted against you)`);
  return parts.join(" · ");
}

export function ProductTestPage() {
  const initialUrl = new URLSearchParams(window.location.search).get("url") ?? "";
  const [url, setUrl] = useState(initialUrl);
  const [phase, setPhase] = useState<"idle" | "running" | "done" | "error">(initialUrl ? "running" : "idle");
  const [result, setResult] = useState<TestResult | null>(null);
  const [error, setError] = useState("");
  const [retryable, setRetryable] = useState(false);
  const ran = useRef(false);
  const [std, setStd] = useState<StandardRun | null>(null);
  const [stdPhase, setStdPhase] = useState<"idle" | "running" | "done">("idle");

  async function runStandard(target: string) {
    setStdPhase("running");
    setStd(null);
    try {
      const res = await fetch("/api/product-test/standard", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ url: target, slug: "coffee" }),
      });
      const data = (await res.json()) as StandardRun;
      setStd(data);
    } catch {
      setStd({ ok: false, productUrl: target, error: "Network error — try again." });
    }
    setStdPhase("done");
  }

  async function run(target: string, force = false) {
    setPhase("running");
    setError("");
    setRetryable(false);
    setResult(null);
    try {
      const res = await fetch("/api/product-test", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ url: target, force }),
      });
      const data = (await res.json()) as TestResult & { error?: string };
      if (!res.ok || !data.ok) {
        setError(data.error || "Couldn't run the test on that URL.");
        setRetryable(Boolean(data.retryable));
        setPhase("error");
        return;
      }
      setResult(data);
      setStd(null);
      setStdPhase("idle");
      // Remember which test this was, so a later "Connect Shopify" click can be tied
      // back to it. The token is the server's own unguessable id and the host is
      // already public; neither identifies a person. Same pattern as `al_last_run`.
      try {
        if (data.testToken) localStorage.setItem("al_last_test_token", data.testToken);
        localStorage.setItem("al_last_test_host", new URL(/^https?:\/\//i.test(target) ? target : `https://${target}`).host);
      } catch { /* private mode / bad URL — telemetry is optional */ }
      setPhase("done");
    } catch {
      setError("Network error — try again.");
      setPhase("error");
    }
  }

  useEffect(() => {
    if (initialUrl && !ran.current) {
      ran.current = true;
      run(initialUrl);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function submit(e?: React.FormEvent) {
    e?.preventDefault();
    const q = url.trim();
    if (!q) return;
    navigate(`/test?url=${encodeURIComponent(q)}`);
    run(q);
  }

  // The headline counts ONLY merchant-addressable gaps. Surfaces we can't reach are
  // never held against the store (that's our access limit, not their omission).
  const unresolved = result ? result.notProvenCount : 0;

  return (
    <div className="scanpage pt-page">
      <h1 className="report-headline">Can an AI buyer verify this product?</h1>
      <p className="muted" style={{ marginTop: -6 }}>
        One product. One buyer task. Every requirement proven from your public store data — or honestly marked unproven.
      </p>

      <form className="hero-form" style={{ margin: "18px 0 8px" }} onSubmit={submit}>
        <input
          type="text" inputMode="url" value={url}
          onChange={(e) => setUrl(e.target.value)}
          placeholder="Paste a Shopify product URL"
          aria-label="Shopify product URL"
        />
        <button type="submit" className="btn btn-primary" disabled={phase === "running"}>
          {phase === "running" ? "Running…" : "Run test"}
        </button>
      </form>

      {phase === "running" && (
        <div className="card scan-running">
          <div className="spinner" />
          <h2>Running your test…</h2>
          <p className="muted">Reading your public product data and checking each buyer requirement. A few seconds.</p>
        </div>
      )}

      {/* ⚠️ THE REFUSAL IS A TEACHING SURFACE, NOT AN ERROR BANNER. Measured against
          production before changing it: `https://www.nike.com/t/air-force-1` and
          `https://klatchcoffee.com` (a real Shopify STORE root) returned the IDENTICAL
          red banner — "Paste a Shopify product URL — it should contain /products/…" —
          because the discriminator is the PATH, not the platform. A stranger's first
          ninety seconds can easily be spent entirely on this screen, and it currently
          tells them nothing about what the product does or why it needs that URL. The
          two cases are now told apart client-side, from the shape of what they typed. */}
      {phase === "error" && (() => {
        const typed = (url.trim() || initialUrl);
        const looksLikeUrl = /\./.test(typed);
        const hasProductPath = /\/products\//i.test(typed);
        const storeRoot = looksLikeUrl && !hasProductPath;
        const isBadUrl = /Shopify product URL/i.test(error);
        if (!isBadUrl) {
          return (
            <div className="banner-error" role="alert" style={{ marginTop: 16 }}>
              {error}
              {/* An upstream rate limit is transient and not a verdict on the store, so
                  the honest affordance is a retry rather than a dead end (V2 §2.3). */}
              {retryable && <> <button className="as-link" onClick={() => run(typed, true)}>Try again</button></>}
            </div>
          );
        }
        return (
          <div className="card pt-guide" role="status" style={{ marginTop: 16 }}>
            <h2>{storeRoot ? "That's a store, not a product page." : "This test needs a product page."}</h2>
            <p>
              AisleLens tests <b>one product at a time</b>, because that is the unit a buyer
              actually decides on: it reads that product's own public data and reports, per
              requirement, what the page proves and what it doesn't — with the sentence it
              was proven from.
            </p>
            {storeRoot ? (
              <p>
                Open any product on <code>{typed.replace(/^https?:\/\//, "").replace(/\/$/, "")}</code>{" "}
                and paste that address. On a Shopify store it will contain{" "}
                <code>/products/</code> — for example{" "}
                <code>{typed.replace(/\/$/, "")}/products/your-product</code>.
              </p>
            ) : (
              <p>
                The engine reads Shopify's public product endpoints, so today it needs a
                Shopify store's product URL — one containing <code>/products/</code>. Other
                platforms aren't supported yet; that is a limit of what we've built, not a
                judgement about the store.
              </p>
            )}
            <p className="muted">
              Want to see one first? <a href="/demo">Here's a real result on a real store</a>,
              run against a published buying standard. Or read{" "}
              <a href={COFFEE_STANDARD_URL}>the standard itself</a> — every question, and what
              counts as evidence for it, before any test runs.
            </p>
          </div>
        );
      })()}

      {phase === "done" && result && (
        <div className="testcard pt-result" style={{ maxWidth: 720, margin: "18px 0 0" }}>
          <div className="testcard-head">
            <span className="tc-dot" aria-hidden /> BUYER TEST
            {result.storeName ? ` · ${result.storeName}` : ""}
            {result.productName ? ` · ${result.productName}` : ""}
          </div>
          {/* THE LAYER SAYS WHAT IT IS. Until v4.1 this table was unlabelled, so a reader
              had no way to tell a generated buyer task from a published standard — and it
              was always the former. Said without apology: a per-product task with a
              published error rate is a strong thing, and the sentence that follows is the
              one that makes the standard button make sense. */}
          <div className="pt-layer">
            <b>General buyer task.</b> These requirements were generated for this specific
            product from what a buyer needs settled — not taken from a published standard.
            The engine's measured false-pass rate on a broad sample of real stores is
            published <a href={COFFEE_STANDARD_URL}>on the standard's page</a>.
          </div>
          <div className="testcard-task"><b>Task:</b> {result.task}</div>

          {/* No "FAILED" verdict: the unresolved count is the same fact without the
              accusation. Crimson stays on the individual unproven rows. */}
          <div className={`pt-outcome ${unresolved === 0 ? "clean" : ""}`}>
            {unresolved === 0
              ? "RESULT: every requirement we could check from public data is proven"
              : `RESULT: ${unresolved} of ${result.total} requirement${unresolved === 1 ? "" : "s"} could not be proven from your public store data`}
          </div>
          <div className="pt-breakdown">{breakdown(result)}</div>

          {/* A partial test says so, up front. The affected rows already carry the
              accurate per-row reason; this makes the whole result legible without
              the merchant having to infer it (V2 §2.3). */}
          {result.degraded && (
            <div className="pt-degraded" role="status">
              <b>Partial test.</b> Some of this store's product endpoints were limiting automated
              requests while we ran, so we couldn't read every surface. The rows below say which.
              That's an upstream limit rather than something about this store —{" "}
              <button className="as-link" onClick={() => run(result.productUrl, true)}>run it again</button> in a few minutes for the full picture.
            </div>
          )}

          {result.cached && result.testedAt && (
            <div className="pt-cached">
              Tested {timeAgo(result.testedAt)} · <button className="as-link" onClick={() => run(result.productUrl, true)}>Run again</button>
            </div>
          )}

          <table className="pt-table">
            <thead><tr><th>Buyer requirement</th><th>Result</th></tr></thead>
            <tbody>{result.assertions.map((a, i) => <Row a={a} key={i} />)}</tbody>
          </table>

          {/* ---- THE PUBLISHED STANDARD, one explicit click away ---------------- */}
          <div className="pt-standard">
            {stdPhase === "idle" && (
              <>
                <b>{looksLikeCoffee(result)
                  ? `This looks like coffee — there is a published standard for it.`
                  : `Is there a published standard for this product?`}</b>
                <p>
                  {looksLikeCoffee(result)
                    ? `AisleLens Coffee Standard ${COFFEE_STANDARD_VERSION} is a fixed, content-hashed set of buyer questions with the evidence rules for each one. Running it gives you entry IDs you can cite, and how many of 100 real coffee stores answer each question.`
                    : `Published standards exist per category. Coffee Standard ${COFFEE_STANDARD_VERSION} is the one published today — it may not apply here, and if it doesn't, it will say so and name the signal it used.`}
                </p>
                <button className="btn" onClick={() => runStandard(result.productUrl)}>
                  Run Coffee Standard {COFFEE_STANDARD_VERSION} against this product
                </button>
                <p className="pt-cachenote">
                  Reads the page again and is never served from cache, so it takes a few
                  seconds and is limited to a few runs per quarter-hour.
                </p>
              </>
            )}

            {stdPhase === "running" && (
              <div className="scan-running"><div className="spinner" />
                <p className="muted">Running the published standard…</p></div>
            )}

            {stdPhase === "done" && std && (
              <div className="pt-stdresult">
                {/* NOT APPLICABLE — a result, not an error, and the one that teaches
                    what a published standard is. `unknown_category` and `out_of_category`
                    are deliberately different sentences: only one is about the merchant. */}
                {std.notApplicable && (
                  <>
                    <b>Coffee Standard {COFFEE_STANDARD_VERSION} does not cover this product.</b>
                    <p>
                      {std.notApplicable.verdict === "out_of_category"
                        ? <>We read this page's category as <code>{std.notApplicable.text}</code> from its {std.notApplicable.signal.replace(/_/g, " ")}, which is outside the standard's scope. That is not a finding about the store — the questions simply don't arise.</>
                        : <>We could not classify this page from its product type, structured data, breadcrumb or title, so we will not assert that a coffee standard applies to it. An unclassifiable page and an out-of-category one are different things, and only the second is a statement about the product.</>}
                    </p>
                    <p className="muted">
                      The general buyer task above still ran, and its result stands. A standard
                      for this category is not published yet — <a href="/standards">the ones that are, are here</a>.
                    </p>
                  </>
                )}

                {!std.ok && !std.notApplicable && (
                  <>
                    <b>Couldn't run the standard.</b>
                    <p>{std.error ?? "Something went wrong."}{" "}
                      {std.retryable && <button className="as-link" onClick={() => runStandard(result.productUrl)}>Try again</button>}</p>
                  </>
                )}

                {std.ok && std.result && std.standard && (
                  <>
                    <div className="pt-stdhead">
                      <b>{std.standard.title}</b>
                      <div className="pt-stdmeta">
                        <a href={std.standard.url}>{std.standard.id} v{std.standard.version}</a>
                        {" · "}content hash <code>{std.standard.hash.slice(0, 12)}</code>
                        {" · "}<a href={`${std.standard.url}/standard.json`}>the artifact as JSON</a>
                        {std.ranAt ? <> · run {new Date(std.ranAt).toISOString().replace("T", " ").slice(0, 16)}Z</> : null}
                      </div>
                      <p className="muted">
                        Every row below is an entry in that document. Click any entry ID to read
                        what counts as evidence for it, what does not, and which surface decides
                        when two disagree — the same text this run was held to.
                      </p>
                    </div>
                    <table className="pt-table">
                      <thead><tr><th>The buyer's question</th><th>Result</th></tr></thead>
                      <tbody>
                        {std.result.assertions.map((a, i) => {
                          const peer = std.peers?.find((x) => x.label === a.label || x.entryId === a.label);
                          const id = peer?.entryId;
                          const passed = a.status === "pass_evidenced" || a.status === "pass_no_blocking";
                          return (
                            <tr className={`pt-row pt-${a.status}`} key={i}>
                              <td className="pt-req">
                                {a.label}
                                {id && std.entryUrls?.[id] && (
                                  <div className="pt-entryid"><a href={std.entryUrls[id]}>{id}</a></div>
                                )}
                              </td>
                              <td className="pt-res">
                                <span className="pt-mark" aria-hidden>{RESULT_MARK[a.status]}</span>
                                <span>
                                  <b>{RESULT_LABEL[a.status]}</b>
                                  <div className="pt-detail">{a.detail}</div>
                                  {a.evidenceQuote && (
                                    <div className="pt-quote">“{a.evidenceQuote}”{a.evidenceSurface ? <span className="pt-src"> — {a.evidenceSurface}</span> : null}</div>
                                  )}
                                  {/* THE PEER LINE. Rendered ONLY here, never on the general
                                      result — the rates are per-ENTRY measurements of this
                                      standard, and attaching them to generated rows would be
                                      inventing a correspondence. */}
                                  {peer && <div className="pt-peer">{peerSentence(peer, passed)}</div>}
                                </span>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                    <p className="pt-stdfoot">
                      Peer figures are the standard's own published measurement over 100 real
                      coffee products across 77 storefronts, every passing row read back
                      individually. The method, the sample and this standard's measured
                      false-pass rate are on <a href={std.standard.url}>its page</a>.
                    </p>
                  </>
                )}
              </div>
            )}
          </div>

          <div className="pt-trace">
            <b>Evidence trace:</b> AisleLens checked {result.surfacesChecked.join(", ")}.
            {result.notInspectable.length > 0 && (
              <> <i>Not inspectable without store access: {result.notInspectable.join(", ")}. We do not report these as missing.</i></>
            )}
          </div>

          {result.suggestedCorrections.length > 0 && (
            <div className="pt-suggest">
              <b>Suggested {result.suggestedCorrections.length === 1 ? "correction" : "corrections"}:</b>
              <ul className="pt-fixlist">
                {result.suggestedCorrections.map((c, i) => <li key={i}>{c}</li>)}
              </ul>
            </div>
          )}

          {/* Requirements public data can't decide are the INSTALL ARGUMENT, not
              blind rows in the merchant's result table. */}
          <div className="pt-cta">
            <div className="pt-auth">
              <b>What authenticated testing adds</b>
              <p>
                Merchant-confirmed product facts · metafield evidence · full policy data · the fix,
                the rerun, and permanent regression tests.
                {result.deferred.length > 0 && (
                  <> <span className="muted">Also checkable with access: {result.deferred.map((d) => d.label.toLowerCase()).join(", ")}.</span></>
                )}
              </p>
            </div>
            {/* The ONE funnel-step CTA: it follows a completed test, so a click here
                has an originating test to attribute it to. Every other ConnectShopify
                on the site deliberately does not count. */}
            <ConnectShopify className="btn btn-primary" label="Connect Shopify to confirm, fix, and rerun" countAsFunnelStep />
            {/* ⚠️ THE LINE THAT WAS HERE SOLD THE RETIRED PRODUCT, in the last sentence a
                visitor reads: "how live AI assistants currently answer questions like this
                in your category — and which stores they send buyers to instead." It was
                also outside the lint surface entirely (not in PUBLIC_MARKETING_STRINGS), so
                no gate could see it. Replaced with the thing that is actually true of this
                result and is the reason to connect: the same contract, re-run, as proof. */}
            <p className="pt-enrich"><i>Connecting re-runs this exact contract with your metafields and policy data readable, so a fix can be proven rather than asserted.</i></p>
          </div>
        </div>
      )}

      {(phase === "done" || phase === "error") && (
        <p className="muted" style={{ fontSize: 12.5, marginTop: 18 }}>
          This test uses only your public store data. It reports what an AI buyer can verify — not what is true about your product. <Link to="/methodology">How testing works →</Link>
        </p>
      )}
    </div>
  );
}
