import type { ShoppingTaskContract } from "./types.js";
import { DEV_SHOP_ID } from "./contract.js";
import { PRIMARY_PRODUCT_ID, SECONDARY_PRODUCT_ID } from "./contract2.js";

// ===========================================================================
// STAGE 3 — PRE-REGISTERED MANUAL CONTRACTS (Gate B control arm, spec 4.5).
//
// CONTAMINATION CONTROL (Rule 5): these two contracts were authored from the
// seeded catalog snapshot and Stage 2 materials ONLY, and committed BEFORE any
// code path in this session read, fetched, or parsed probe observations. The
// commit hash + file hash are recorded in preregistration.json and verified
// mechanically by the probe-parsing guard (test 34). Do not edit this file
// after pre-registration.
// ===========================================================================

/** "Travel deodorant" manual contract — deliberately NOT a copy of
 *  stage2PrimaryContract: different required variant (1 oz Travel), different
 *  claim attribute (baking-soda-free, evidenced mid-paragraph in the seeded
 *  copy), tighter price cap, delivery timing. */
export const manualDeodorantContract: ShoppingTaskContract = {
  id: "stage3-manual-travel-deodorant",
  version: "2",
  objective: "select_purchase_ready_product",
  productScope: {
    shopId: DEV_SHOP_ID,
    productId: PRIMARY_PRODUCT_ID,
    variantId: "gid://shopify/ProductVariant/45972061847654", // Unscented / 1 oz Travel
  },
  hardConstraints: [
    {
      id: "m1-baking-soda-free",
      attribute: "baking_soda_free",
      operator: "must_be_true",
      expectedValue: true,
      evidenceRequired: true,
      acceptableSurfaces: ["product_description", "product_metafields", "structured_data", "faq"],
    },
    {
      id: "m2-travel-variant-purchasable",
      attribute: "required_variant_in_stock",
      operator: "must_be_true",
      expectedValue: true,
      evidenceRequired: true,
      acceptableSurfaces: ["product_variants"],
    },
    {
      id: "m3-price",
      attribute: "variant_price",
      operator: "less_than",
      expectedValue: 15.0,
      evidenceRequired: true,
      acceptableSurfaces: ["product_variants", "structured_data"],
    },
    {
      id: "m4-delivery-resolvable",
      attribute: "delivery_timing",
      operator: "must_be_resolvable",
      evidenceRequired: true,
      acceptableSurfaces: ["shipping_policy", "faq"],
    },
  ],
  successConditions: { correctProductRequired: true, allHardConstraintsSatisfied: true, evidenceRequiredForEveryFact: true },
  limits: { maxSteps: 14, maxToolCalls: 12, maxOutputTokens: 3500 },
};

/** Harbor Lane shave-soap manual contract: vegan + tallow-free + price + delivery. */
export const manualShaveSoapContract: ShoppingTaskContract = {
  id: "stage3-manual-shave-soap",
  version: "2",
  objective: "select_purchase_ready_product",
  productScope: { shopId: DEV_SHOP_ID, productId: SECONDARY_PRODUCT_ID },
  hardConstraints: [
    {
      id: "s1-vegan",
      attribute: "vegan",
      operator: "must_be_true",
      expectedValue: true,
      evidenceRequired: true,
      acceptableSurfaces: ["product_description", "product_metafields", "structured_data", "faq"],
    },
    {
      id: "s2-tallow-free",
      attribute: "tallow_free",
      operator: "must_be_true",
      expectedValue: true,
      evidenceRequired: true,
      acceptableSurfaces: ["product_description", "product_metafields", "structured_data", "faq"],
    },
    {
      id: "s3-price",
      attribute: "variant_price",
      operator: "less_than",
      expectedValue: 30.0,
      evidenceRequired: true,
      acceptableSurfaces: ["product_variants", "structured_data"],
    },
    {
      id: "s4-delivery-resolvable",
      attribute: "delivery_timing",
      operator: "must_be_resolvable",
      evidenceRequired: true,
      acceptableSurfaces: ["shipping_policy", "faq"],
    },
  ],
  successConditions: { correctProductRequired: true, allHardConstraintsSatisfied: true, evidenceRequiredForEveryFact: true },
  limits: { maxSteps: 14, maxToolCalls: 12, maxOutputTokens: 3500 },
};

export const MANUAL_CONTRACTS = [manualDeodorantContract, manualShaveSoapContract];
